Also ignore NoClassDefFoundError when checking for Optifine. ClassNotFoundException is thrown when the class passed to "Class.forName" is not found. NoClassDefFoundError is thrown when the class is found, but a linked dependency class of that class is not found. E.g. because Optifine for a wrong MC version is in the classpath.
Also add missing override statement